name: Basic CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-php-82:
    name: Test Suite (PHP 8.2)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: curl, json, mbstring, sockets, xml
        coverage: xdebug
        tools: composer:v2
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    
    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: php-8.2-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: php-8.2-composer-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
    
    - name: Create storage directories
      run: |
        mkdir -p storage/logs storage/sessions storage/sessions/temp_sessions
        chmod 755 storage/logs storage/sessions storage/sessions/temp_sessions
    
    - name: Run PHP syntax check
      run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;
    
    - name: Run PHPUnit (Unit Tests)
      run: vendor/bin/phpunit tests/unit/ --verbose
    
    - name: Run PHPUnit (Integration Tests)
      run: vendor/bin/phpunit tests/integration/ --verbose
    
    - name: Run PHPUnit with Coverage
      run: |
        vendor/bin/phpunit tests/unit/ tests/integration/ \
          --coverage-clover=coverage.xml \
          --coverage-text \
          --coverage-html=coverage-report
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false 