name: CI/CD Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  schedule:
    # Run tests daily at 2 AM UTC to catch dependency issues
    - cron: '0 2 * * *'

jobs:
  test:
    name: Test Suite (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']
        include:
          - php-version: '8.2'
            coverage: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: curl, json, mbstring, sockets, xml
        coverage: ${{ matrix.coverage && 'xdebug' || 'none' }}
        tools: composer:v2
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    
    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: php-${{ matrix.php-version }}-composer-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
    
    - name: Create storage directories
      run: |
        mkdir -p storage/logs storage/sessions storage/sessions/temp_sessions
        chmod 755 storage/logs storage/sessions storage/sessions/temp_sessions
    
    - name: Run PHP syntax check
      run: find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \;
    
    - name: Run PHPUnit (Unit Tests)
      run: vendor/bin/phpunit tests/unit/ --verbose
    
    - name: Run PHPUnit (Integration Tests)
      run: vendor/bin/phpunit tests/integration/ --verbose
    
    - name: Run PHPUnit with Coverage (PHP 8.2 only)
      if: matrix.coverage
      run: |
        vendor/bin/phpunit tests/unit/ tests/integration/ \
          --coverage-clover=coverage.xml \
          --coverage-text \
          --coverage-html=coverage-report
    
    - name: Upload coverage to Codecov
      if: matrix.coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Archive coverage report
      if: matrix.coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-report/
        retention-days: 30

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
    
    - name: Run security audit
      run: |
        # Check for known vulnerabilities in dependencies
        composer audit --format=json || true
    
    - name: Secret scanning
      run: |
        # Simple secret scanning - check for common patterns
        echo "Running basic secret pattern checks..."
        if grep -r -E "(GOCSPX-|sk_live_|sk_test_|pk_live_|pk_test_)" . --exclude-dir=vendor --exclude-dir=.git || true; then
          echo "⚠️ Potential secrets found - please review"
        else
          echo "✅ No obvious secret patterns detected"
        fi
    
    - name: Dependency review
      uses: actions/dependency-review-action@v4
      if: github.event_name == 'pull_request'

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer:v2
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
    
    - name: Create storage directories (needed for some analysis)
      run: |
        mkdir -p storage/logs storage/sessions storage/sessions/temp_sessions
        chmod 755 storage/logs storage/sessions storage/sessions/temp_sessions
    
    - name: Check code style (PSR-12)
      run: |
        composer cs:check || echo "Code style issues found (non-blocking in CI)"
    
    - name: Run static analysis
      run: |
        composer stan || echo "Static analysis issues found (non-blocking in CI)"
    
    - name: Run mutation testing (sample)
      run: |
        # Run a small subset for CI to avoid timeouts
        timeout 300 composer test:mut || echo "Mutation testing completed with issues (non-blocking in CI)"
    
    - name: Validate .gitignore
      run: |
        # Ensure sensitive files are properly ignored
        if git ls-files | grep -E "(client_secret\.json|\.env|sess_|\.log)$"; then
          echo "❌ Sensitive files found in repository!"
          exit 1
        else
          echo "✅ No sensitive files found in repository"
        fi 