name: Simple Test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  basic-test:
    name: Basic Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: curl, json, mbstring, sockets, xml
        tools: composer:v2
    
    - name: Check PHP version
      run: php --version
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
    
    - name: Create storage directories
      run: |
        mkdir -p storage/logs storage/sessions storage/sessions/temp_sessions
        chmod 755 storage/logs storage/sessions storage/sessions/temp_sessions
    
    - name: Run basic test
      run: vendor/bin/phpunit tests/unit/ArraySessionTest.php --verbose 